### PR TITLE
New pieret

### PR DESCRIPTION
**Pull request by halouzkovap**
add h2 db to project, for testing

### CODE REVIEW

**Review by JoseAdemar — COMMENTED** [review]
Hi Petra I saw here that you are working on the database connection, is this connection ready? It's working ? If so, I will merge into the master branch.

**Comment by halouzkovap** [comment]
i did 2 connection, one is inmemory DB, this db is for testing purposes. and my sql connection. name for db is Beautyproject, and password and username is save in enviroment variable

**Comment by JoseAdemar** [comment]
Ok I'm goingg to merge

**Comment by JoseAdemar** [comment]
I did the merge from the  Pull request  that you sent me

**Pull request merged**
